version: "2"
services:

  dev:
    image: 428466588005.dkr.ecr.eu-west-2.amazonaws.com/phpwkhtmltopdf-server:5.6.38-cli
    working_dir: /opt/phpwkhtmltopdf-server
    volumes:
      - .:/opt/phpwkhtmltopdf-server
      - ~/.config/composer:/tmp/composer
      - ~/.cache/composer:/tmp/composer-cache
    env_file:
        - .env
    environment:
      COMPOSER_HOME: /tmp/composer
      COMPOSER_CACHE_DIR: /tmp/composer-cache
    links:
      - app

  app:
    image: 428466588005.dkr.ecr.eu-west-2.amazonaws.com/phpwkhtmltopdf-server:5.6.38-apache
    working_dir: /opt/phpwkhtmltopdf-server
    volumes:
      - .:/opt/phpwkhtmltopdf-server
      - ./docker/apache-vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php.ini:/usr/local/etc/php/conf.d/90-php.ini
    env_file:
        - .env
    ports:
      - "${HOST_HTTP_PORT}:80"
