version: "3"
services:

  dev:
    image: docker.deko-dev.com/phpwkhtmltopdf-server/dev:5.6.38-cli-0.1.0
    working_dir: /opt/phpwkhtmltopdf-server
    volumes:
      - .:/opt/phpwkhtmltopdf-server
      - ~/.config/composer:/tmp/composer
      - ~/.cache/composer:/tmp/composer-cache
    env_file:
        - .env
    environment:
      COMPOSER_HOME: /tmp/composer
      COMPOSER_CACHE_DIR: /tmp/composer-cache
    links:
      - app

  app:
    image: docker.deko-dev.com/phpwkhtmltopdf-server/base:5.6.38-apache-0.1.0
    working_dir: /opt/phpwkhtmltopdf-server
    volumes:
      - .:/opt/phpwkhtmltopdf-server
      - ./docker/apache-vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php.ini:/usr/local/etc/php/conf.d/90-php.ini
    env_file:
        - .env
    ports:
      - "${HOST_HTTP_PORT}:80"
